### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Nithmr/NithResultApp#22]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by Barathwaja** [comment]
may i?

**Comment by Rishabh04-02** [comment]
@Barathwaja yes you can.

**Comment by Barathwaja** [comment]
@Rishabh04-02  PR #23 do let me know if you need any changes.

**Comment by Rishabh04-02** [comment]
@Barathwaja Thanks for contributing 👍.
